"""Bounded control allocation for the three-corner RCS layout."""

# Each column is [Fx, Fy, Fz, Tx, Ty, Tz] for one unit-duty, 1 N nozzle.
# Corner A (-0.75, -0.60, -0.50): +X, +Y
# Corner B (-0.75, -0.60, +0.50): -X, +Z
# Corner C (+0.75, +0.60, -0.50): -Y, -Z
THRUSTER_WRENCHES = (
    (1.0, 0.0, 0.0, 0.0, -0.50, 0.60),
    (0.0, 1.0, 0.0, 0.50, 0.0, -0.75),
    (-1.0, 0.0, 0.0, 0.0, -0.50, -0.60),
    (0.0, 0.0, 1.0, -0.60, 0.75, 0.0),
    (0.0, -1.0, 0.0, -0.50, 0.0, -0.75),
    (0.0, 0.0, -1.0, -0.60, 0.75, 0.0),
)


def wrench_from_duty(duty_cycle):
    """Return the body-frame wrench generated by six normalized duties."""
    if len(duty_cycle) != 6:
        raise ValueError("Exactly six RCS duty values are required.")
    return tuple(sum(duty * column[row] for duty, column in
                     zip(duty_cycle, THRUSTER_WRENCHES)) for row in range(6))


def allocate_wrench(desired_wrench, force_weight=0.25, torque_weight=1.0,
                    iterations=240):
    """Allocate a desired wrench into duty values constrained to [0, 1].

    A deterministic projected-gradient solve is sufficient for six nozzles and
    avoids an extra numerical-optimizer dependency.  Torque is weighted more
    strongly than force by default, so wheel desaturation may translate the
    spacecraft while still unloading its angular momentum.
    """
    if len(desired_wrench) != 6:
        raise ValueError("A wrench must contain Fx, Fy, Fz, Tx, Ty, Tz.")
    if force_weight <= 0.0 or torque_weight <= 0.0:
        raise ValueError("Allocation weights must be positive.")

    weights = (force_weight, force_weight, force_weight,
               torque_weight, torque_weight, torque_weight)
    weight_squared = tuple(weight * weight for weight in weights)
    duties = [0.0] * 6
    # Conservative upper bound for the gradient Lipschitz constant.
    lipschitz = 2.0 * sum(
        weight_squared[row] * column[row] * column[row]
        for row in range(6) for column in THRUSTER_WRENCHES)
    step = 1.0 / lipschitz

    for _ in range(iterations):
        actual = wrench_from_duty(duties)
        residual = [actual[row] - desired_wrench[row] for row in range(6)]
        next_duties = []
        for column_index, column in enumerate(THRUSTER_WRENCHES):
            gradient = 2.0 * sum(
                weight_squared[row] * residual[row] * column[row]
                for row in range(6))
            next_duties.append(min(1.0, max(0.0,
                                             duties[column_index] - step * gradient)))
        duties = next_duties
    return duties
